nomina/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.decorators import login_required, permission_required
from django.views.generic import TemplateView

from nomina import views
from nomina.views import *

urlpatterns = [
    #Home
    path('', views.home, name='home'),
    path('proyeccion/', views.proyeccion_list, name='proyeccion'),

    #FONACOT
    path('fonacots/', views.fonacot_list, name='fonacots'),
    path('fonacot/', views.fonacot_nuevo, name='fonacot-nuevo'),
    path('fonacot/<int:pk>/', views.fonacot_editar, name='fonacot-editar'),
    path('fonacot/<int:pk>/eliminar/', views.fonacot_eliminar, name='fonacot-eliminar'),
    path('fonacot/exportar-txt/', views.fonacot_exportar_txt, name='fonacot-exportar-txt'),
    path('fonacot/exportar-csv/', views.fonacot_exportar_csv, name='fonacot-exportar-csv'),

    #Empleados
    path('empleados/', views.empleados_list, name='empleados'),
    path('empleado/', login_required(EmpleadoCreateView.as_view()), name='empleado-nuevo'),
    path('empleado/<int:pk>/', login_required(EmpleadoUpdateView.as_view()), name='empleado-editar'),
    path('empleado/<int:pk>/eliminar/', views.empleado_eliminar, name='empleado-eliminar'),
    path('empleados/eliminar/', views.empleados_eliminar, name='empleados-eliminar'),
    path('empleados/reporte/', views.empleados_reporte, name='empleados-reporte'),
    path('empleados/sueldo/', views.sueldo, name='sueldo'),

    #Departamentos
    path('departamentos/', views.departamentos_list, name='departamentos'),
    path('departamento/', views.departamento_nuevo, name='departamento-nuevo'),
    path('departamento/<int:pk>/', views.departamento_editar, name='departamento-editar'),
    path('departamento/<int:pk>/eliminar/', views.departamento_eliminar, name='departamento-eliminar'),
    path('departamento/<int:pk>/subir/', views.departamento_subir, name='departamento-subir'),
    path('departamento/<int:pk>/bajar/', views.departamento_bajar, name='departamento-bajar'),

    #Puestos
    path('puestos/', views.puestos_list, name='puestos'),
    path('puesto/', views.puesto_nuevo, name='puesto-nuevo'),
    path('puesto/<int:pk>/', views.puesto_editar, name='puesto-editar'),
    path('puesto/<int:pk>/eliminar/', views.puesto_eliminar, name='puesto-eliminar'),

    #Catorcenas
    path('catorcenas/', views.catorcenas_list, name='catorcenas'),
    path('catorcenas/sincronizar/', views.catorcena_sincronizar, name='catorcenas-sincronizar'),

    #Partidas
    path('partidas/', views.partidas_list, name='partidas'),
    path('partida/', views.partida_nuevo, name='partida-nuevo'),
    path('partida/<int:pk>/', views.partida_editar, name='partida-editar'),
    path('partida/<int:pk>/eliminar/', views.partida_eliminar, name='partida-eliminar'),
    path('partida/<int:pk>/subir/', views.partida_subir, name='partida-subir'),
    path('partida/<int:pk>/bajar/', views.partida_bajar, name='partida-bajar'),

    #Estructuras
    path('estructuras/', views.estructuras_list, name='estructuras'),
    path('estructuras/sueldos/', views.estructura_sueldos_incr, name='estructuras-sueldos'),
    path('estructura/', views.estructura_nuevo, name='estructura-nuevo'),
    path('estructura/<int:pk>/', views.estructura_editar, name='estructura-editar'),
    path('estructura/<int:pk>/eliminar/', views.estructura_eliminar, name='estructura-eliminar'),

    #ISR
    path('isrs/', views.isrs_list, name='isrs'),
    path('isr/', views.isr_nuevo, name='isr-nuevo'),
    path('isr/<int:pk>/', views.isr_editar, name='isr-editar'),
    path('isr/<int:pk>/eliminar/', views.isr_eliminar, name='isr-eliminar'),

    #Subsidio
    path('subsidios/', views.subsidios_list, name='subsidios'),
    path('subsidio/', views.subsidio_nuevo, name='subsidio-nuevo'),
    path('subsidio/<int:pk>/', views.subsidio_editar, name='subsidio-editar'),
    path('subsidio/<int:pk>/eliminar/', views.subsidio_eliminar, name='subsidio-eliminar'),

    #Planes
    path('planes/', views.planes_list, name='planes'),
    path('plan/<int:pk>/', views.plan_editar, name='plan-editar'),
    path('plan/<int:pk>/cargar/', views.plan_cargar, name='plan-cargar'),
    path('plan/<int:pk>/clonar/', views.plan_clonar, name='plan-clonar'),
    path('plan/<int:pk>/eliminar/', views.plan_eliminar, name='plan-eliminar'),
    
    #AUTH
    path('login/', SigaLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(template_name='nomina/logout.html'), name='logout'),

    #SCRIPTS
    path('scripts/', views.scripts, name='scripts'),
    path('scripts/departamentos/', views.scripts_departamentos, name='scripts-departamentos'),
    path('scripts/puestos/', views.scripts_puestos, name='scripts-puestos'),
    path('scripts/estructuras/', views.scripts_estructuras, name='scripts-estructuras'),
    path('scripts/empleados/', views.scripts_empleados, name='scripts-empleados'),
    path('scripts/partidas/', views.scripts_partidas, name='scripts-partidas'),
    path('scripts/departamentos-plan/', views.scripts_departamentos_plan, name='scripts-departamentos-plan'),
    path('scripts/puestos-plan/', views.scripts_puestos_plan, name='scripts-puestos-plan'),
    path('scripts/plan-sincronizar/', views.scripts_plan_sincronizar, name='scripts-plan-sincronizar'),
    path('scripts/plan-sueldos/', views.scripts_plan_sueldos, name='scripts-plan-sueldos'),
    path('scripts/plan-isr/', views.scripts_plan_isr, name='scripts-plan-isr'),
    path('scripts/asimilables/', views.scripts_asimilables, name='scripts-asimilables'),
    path('scripts/consejeros/', views.scripts_consejeros, name='scripts-consejeros'),
    path('scripts/fonacot/', views.scripts_fonacot, name='scripts-fonacot'),
    path('scripts/fonacot-csv/', views.scripts_fonacot_csv, name='scripts-fonacot-csv'),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nomina/models/departamento.py
from django.db import models
from .plan import Plan, DEFAULT_PLAN_ID

class Departamento(models.Model):
    descripcion = models.CharField(max_length=255)
    orden = models.IntegerField(default=0)
    plan = models.ForeignKey(Plan, on_delete=models.RESTRICT, default=DEFAULT_PLAN_ID)

    def __str__(self):
        return self.descripcion

    class Meta:
        ordering = ['orden']

nomina/models/empleado.py
from django.db import models
from django.db.models import Q
import datetime
from datetime import date
from calendar import monthrange

from .plan import Plan, DEFAULT_PLAN_ID
from .tipoempleado import TipoEmpleado
from .departamento import Departamento
from .puesto import Puesto
from .vacaciones import Vacaciones
from .rama import Rama
from .nivel import Nivel

from nomina.models import *

class Estructura(models.Model):
    tipo = models.ForeignKey(TipoEmpleado, on_delete=models.RESTRICT)
    rama = models.ForeignKey(Rama, on_delete=models.RESTRICT)
    nivel = models.ForeignKey(Nivel, on_delete=models.RESTRICT)
    puesto = models.ForeignKey(Puesto, on_delete=models.RESTRICT)
    clave = models.CharField(max_length=255)
    nivel_consecutivo = models.IntegerField()
    nivel_tabular = models.IntegerField()
    sueldo = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    plan = models.ForeignKey(Plan, on_delete=models.RESTRICT, default=DEFAULT_PLAN_ID)

    def __str__(self):
        return '%s - %s' % (self.puesto, self.tipo)
    
    @property
    def empleados(self):
        return Empleado.objects.filter(plan = self.plan, puesto = self.puesto, tipo = self.tipo).count()

class Empleado(models.Model):
    plazas = models.IntegerField(default=1)
    tipo = models.ForeignKey(TipoEmpleado, on_delete=models.RESTRICT)
    numero = models.CharField(max_length=255)
    departamento = models.ForeignKey(Departamento, on_delete=models.RESTRICT)
    puesto = models.ForeignKey(Puesto, on_delete=models.RESTRICT)
    nombre = models.CharField(max_length=255)
    apellido_paterno = models.CharField(max_length=255, blank=True)
    apellido_materno = models.CharField(max_length=255, blank=True)
    vacaciones = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    excedente = models.DecimalField(max_digits=10, decimal_places=3, default=0)
    spen = models.BooleanField(default=False)
    plan = models.ForeignKey(Plan, on_delete=models.RESTRICT, default=DEFAULT_PLAN_ID)

    class Meta:
        ordering = ['departamento__orden']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.periodos = self.periodo_set.all()
        self.fecha_ingreso = self.get_fecha_ingreso()
        self.sueldo = self.get_sueldo()

    def __str__(self):
        return self.nombre
    
    def nombre_completo(self):
        return self.apellido_paterno + ' ' + self.apellido_materno + ' ' + self.nombre

    def get_sueldo(self):
        if self.id:
            estructura = Estructura.objects.filter(tipo = self.tipo, puesto = self.puesto, plan = self.plan).first()
            if estructura:
                return estructura.sueldo     
        return 0
    
    def get_fecha_ingreso(self):
        if len(self.periodos) > 0:
            return self.periodos.first().fecha_ingreso
        return date.today()
    
    def es_incapacitado(self):
        return (self.puesto.descripcion in ['INCAPACITADO PERMANENTE "A"', 'INCAPACITADO PERMAMENTE "B"', 'INCAPACITADO PERMANENTE "C"'])

    def set_dias_vacaciones(self, anio):
        if self.tipo.es_confianza():
            self.dias_vacaciones = self.vacaciones
        else:
            self.dias_vacaciones = 20

    def set_periodos_dias(self):
        dias = 0
        if not self.tipo.es_confianza():
            for periodo in self.periodos:
                dias += periodo.dias

        self.periodos_dias = dias    

    def set_bono(self):
        self.recibe_bono = True
        puestos = ['CONSEJERO PRESIDENTE', 'CONSEJERO ELECTORAL']
        departamentos = ['CONSEJO GENERAL ELECTORAL']
        if (self.puesto.descripcion in puestos) and (self.departamento.descripcion in departamentos):
            self.recibe_bono = False
        
        puestos = ['ENLACE ADMINISTRATIVO', 'DELEGADO MUNICIPAL', 'DELEGADO DISTRITAL']
        if (('CONSEJO DISTRITAL' in self.departamento.descripcion) or (self.puesto.descripcion in puestos)) and (not self.tipo.es_confianza()):
            self.recibe_bono = False

    def set_transporte(self):
        self.recibe_transporte = False
        puestos = ['SECRETARIO FEDATARIO', 'DELEGADO DISTRITAL', 'DELEGADO MUNICIPAL']
        if (self.puesto.descripcion in puestos):
            self.recibe_transporte = True

    def set_gastos(self):
        self.recibe_gastos = False
        puestos = ['CAES', 'SUPERVISOR ELECTORAL']
        if (self.puesto.descripcion in puestos):
            self.recibe_gastos = True

    def mes_dias(self, anio, mes):
        primer_dia_mes = datetime.date(anio, mes, 1)
        ultimo_dia_mes = datetime.date(anio, mes, monthrange(anio, mes)[1])

        mes_dias = 0
        fecha_inicio = 0
        fecha_final = 0

        for periodo in self.periodos:
            #Determinar el mas grande de las dos fechas iniciales
            if periodo.fecha_ingreso > primer_dia_mes:
                fecha_inicio = periodo.fecha_ingreso
            else:
                fecha_inicio = primer_dia_mes

            #Determinar la menor de las dos fechas finales
            if periodo.fecha_baja < ultimo_dia_mes:
                fecha_final = periodo.fecha_baja
            else:
                fecha_final = ultimo_dia_mes
        
            dias_calculo = (fecha_final - fecha_inicio).days + 1

            if dias_calculo > 0:
                mes_dias += dias_calculo

        return mes_dias
    
    def mes_dias_baja(self, anio, mes):
        primer_dia_mes = datetime.date(anio, mes, 1)
        ultimo_dia_mes = datetime.date(anio, mes, monthrange(anio, mes)[1])

        mes_dias = 0

        periodos_empleado = self.periodos.filter(Q(fecha_baja__gte = primer_dia_mes), Q(fecha_baja__lte = ultimo_dia_mes))
        for periodo in periodos_empleado:
            dias_calculo = (periodo.fecha_baja - periodo.fecha_ingreso).days + 1

            if dias_calculo > 0:
                mes_dias += dias_calculo

        return mes_dias

    def set_meses_dias(self, anio):
        self.meses_dias = [0,0,0,0,0,0,0,0,0,0,0,0]
        self.meses_dias_baja = [0,0,0,0,0,0,0,0,0,0,0,0]

        for periodo in self.periodos:
            dia_ingreso = periodo.fecha_ingreso
            dia_baja = periodo.fecha_baja

            while dia_ingreso <= dia_baja:
                self.meses_dias[dia_ingreso.month - 1] += 1
                dia_ingreso = dia_ingreso + datetime.timedelta(days=1)

            self.meses_dias_baja[dia_baja.month - 1] = periodo.dias

    def set_catorcenas_dias(self, catorcenas):
        #Obtiene dias contratados por catorcena
        self.catorcenas_dias = [0] * len(catorcenas)
        i = 0

        for catorcena in catorcenas:
            dias_catorcena = self.get_dias_periodo_catorcena(catorcena)
            self.catorcenas_dias[i] = dias_catorcena
            i += 1
    
    def get_dias_periodo_catorcena(self, catorcena):
        dias_catorcena = 0

        for periodo in self.periodos:
            #Determinar el mas grande de las dos fechas iniciales
            if periodo.fecha_ingreso > catorcena.fecha_inicio:
                fecha_inicio = periodo.fecha_ingreso
            else:
                fecha_inicio = catorcena.fecha_inicio

            #Determinar la menor de las dos fechas finales
            if not periodo.fecha_baja:
                fecha_final = catorcena.fecha_final
            else:
                if periodo.fecha_baja < catorcena.fecha_final:
                    fecha_final = periodo.fecha_baja
                else:
                    fecha_final = catorcena.fecha_final
            
            dias_calculo = (fecha_final - fecha_inicio).days + 1
            if dias_calculo > 0:
                dias_catorcena += dias_calculo

        return dias_catorcena
        
    def set_data_emp(self, anio, catorcenas):
        self.set_dias_vacaciones(anio)
        self.set_bono()
        self.set_periodos_dias()
        self.set_catorcenas_dias(catorcenas)
        self.set_transporte()
        self.set_gastos()

        if not self.tipo.es_confianza():
            self.set_meses_dias(anio)


class Periodo(models.Model):
    empleado = models.ForeignKey(Empleado, on_delete=models.CASCADE)
    fecha_ingreso = models.DateField()
    fecha_baja = models.DateField(null=True, blank=True)

    def __str__(self):
        return '%s al %s (Dias: %s)' % (self.fecha_ingreso, self.fecha_baja, self.dias)

    @property
    def dias(self):
        return (self.fecha_baja - self.fecha_ingreso).days + 1

    class Meta:
        ordering = ['fecha_ingreso']

nomina/models/partida.py
from django.db import models
from .plan import Plan, DEFAULT_PLAN_ID

class Partida(models.Model):
    descripcion = models.CharField(max_length=255)
    codigo = models.IntegerField()
    valor = models.DecimalField(max_digits=10, decimal_places=4, default=0)
    confianza = models.BooleanField(default=True)
    eventual = models.BooleanField(default=True)
    asimilable = models.BooleanField(default=True)
    incapacitado = models.BooleanField(default=True)
    orden = models.IntegerField(default=0)
    plan = models.ForeignKey(Plan, on_delete=models.RESTRICT, default=DEFAULT_PLAN_ID)

    def __str__(self):
        return self.descripcion

    @property
    def descripcion_tipos(self):
        return self.descripcion + " " + self.tipos

    @property
    def tipos(self):
        tipos = []
        if self.confianza:
            tipos.append("Confianza")
        if self.eventual:
            tipos.append("Eventual")
        if self.asimilable:
            tipos.append("Asimilable")
        if self.incapacitado:
            tipos.append("Incapacitado")

        tipos_str = ''

        if len(tipos) == 1:
            tipos_str = '(%s)' % (tipos[0])

        if len(tipos) == 2:
            tipos_str = '(%s, %s)' % (tipos[0], tipos[1])

        if len(tipos) == 3:
            tipos_str = '(%s, %s, %s)' % (tipos[0], tipos[1], tipos[2])

        if len(tipos) == 4:
            tipos_str = '(%s, %s, %s, %s)' % (tipos[0], tipos[1], tipos[2], tipos[3])

        return tipos_str

    class Meta:
        ordering = ['orden']

nomina/models/puesto.py
from django.db import models
from .plan import Plan, DEFAULT_PLAN_ID

class Puesto(models.Model):
    descripcion = models.CharField(max_length=255)
    plan = models.ForeignKey(Plan, on_delete=models.RESTRICT, default=DEFAULT_PLAN_ID)

    def __str__(self):
        return self.descripcion

    class Meta:
        ordering = ['descripcion']

nomina/forms/catorcenas.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Div, Field, Submit
from crispy_forms.bootstrap import FormActions
from nomina.models import *
from .class_select import class_form_select_sm
from .inputs import DateInput

class CatorcenasSyncForm(forms.Form):    
    fecha_inicial = forms.DateField(required=True, widget=DateInput(format=('%Y-%m-%d'), attrs={'class':'form-control-sm','type': 'date'}), label='Fecha de inicio primera catorcena')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Field('fecha_inicial', wrapper_class="col-2"),
            FormActions(
                Submit('save', 'Generar Catorcenas'),
            ),
        )

nomina/forms/class_select.py
class_form_select = {'class':'form-control form-select'}
class_form_select_sm = {'class':'form-control form-select-sm'}

nomina/templates/nomina/planes/content.html
{% extends 'nomina/base_sidebar.html' %}
{% load humanize %}
{% load static %}

{% load auth_extras %}
{% load crispy_forms_tags %}

{% block content %}

{{ form.media }}

<!-- Encabezado -->
<div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Planes</h1>
</div>

<!-- Tabla -->
<div class="table-responsive-sm table-wrapper-planes">
    <table class="table table-striped table-bordered table-hover table-sm">
        <thead class="table-dark">
            <tr>
                <th>Plan</th>
                <th>Partidas</th>
                <th>Departamentos</th>
                <th>Puestos</th>
                <th>Estructuras</th>
                <th>Empleados</th>
                <th class="text-center" style="width:20%;">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for plan in planes %}
                <tr {% if plan.id == request.session.plan %} class="table-dark" {% endif %}>
                    <td>{{plan.descripcion}}</td>
                    <td>{{ plan.partida_set.count }}</td>
                    <td>{{ plan.departamento_set.count }}</td>
                    <td>{{ plan.puesto_set.count }}</td>
                    <td>{{ plan.estructura_set.count }}</td>
                    <td>{{ plan.empleado_set.count }}</td>

                    <td class="text-center">
                        {% if not plan.eliminando and plan.clonado %}
                            <div class="btn-group" role="group">
                                <a href="{% url 'plan-cargar' plan.pk %}" data-id="{{ plan.id }}" style="background-color: #782484; border-color: #782484" class="btn btn-primary btn-sm cargar-modal {% if plan.id == request.session.plan %}disabled" aria-disabled="true {% else %} " data-toggle="tooltip" data-bs-placement="top" title="Cargar {% endif %}"><span data-feather="box"></span></a>
                                <a data-url="{% url 'plan-clonar' plan.pk %}" data-id="{{ plan.id }}" class="btn btn-success btn-sm clonar-modal" data-toggle="tooltip" data-bs-placement="top" title="Clonar"><span data-feather="copy"></span></a>
                                <a data-url="{% url 'plan-editar' plan.pk %}" data-id="{{ plan.id }}" class="btn btn-warning btn-sm editar-modal" data-toggle="tooltip" data-bs-placement="top" title="Modificar"><span data-feather="edit"></span></a>
                                <a data-url="{% url 'plan-eliminar' plan.pk %}" data-id="{{ plan.id }}" class="btn btn-danger btn-sm eliminar-modal {% if plan.id == request.session.plan %}disabled" aria-disabled="true {% else %} " data-toggle="tooltip" data-bs-placement="top" title="Eliminar {% endif %}"><span data-feather="x-square"></span></a>
                            </div>
                        {% else %}
                            <div class="spinner-border spinner-border-sm" role="status"></div>
                            <strong> 
                            {% if plan.eliminando %}
                                Eliminando... 
                            {% else %} 
                                Clonando... 
                            {% endif %} 
                            </strong>
                        {% endif %}
                    </td>
                </tr>
            {% empty %}
                <tr>
                    <td colspan="100%" class="text-center bg-light">Sin planes</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

nomina/templates/nomina/planes/modal-clonar.html
{% load crispy_forms_tags %}

{{ form.media }}

<div class="modal fade" data-bs-backdrop="static" id="clonarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true">
    <form method="post" action="{% url 'plan-clonar' plan.pk %}" id="editar-form" autocomplete="off">
        {% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="editarModalLabel">Clonar Plan - {{ plan.descripcion }}</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                    {% crispy form %}
                </div>
    
                <div class="modal-footer">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" id="submit" class="btn btn-success" >Clonar Plan</button>
                    </div>            
                </div>
            </div>
        </div>
    </form>
</div>

nomina/templates/nomina/planes/modal-editar.html
{% load crispy_forms_tags %}

{{ form.media }}

<div class="modal fade" data-bs-backdrop="static" id="editarModal" tabindex="-1" role="dialog" aria-labelledby="editarModalLabel" aria-hidden="true">
    <form method="post" action="{% url 'plan-editar' plan.pk %}" id="editar-form" autocomplete="off">
        {% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="editarModalLabel">Modificar Plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                    {% crispy form %}
                </div>
    
                <div class="modal-footer">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-outline-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" id="submit" class="btn btn-warning" >Guardar Plan</button>
                    </div>            
                </div>
            </div>
        </div>
    </form>
</div>

nomina/templates/nomina/planes/modal-eliminar.html
<div class="modal fade" data-bs-backdrop="static" id="eliminarModal" tabindex="-1" role="dialog" aria-labelledby="eliminarModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="eliminarModalLabel">¿Esta seguro/a de eliminar el plan?</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>
                    <b>Descripción: </b>{{ plan.descripcion }}
                </p>
            </div>
            <div class="modal-footer">
                <div class="btn-group" role="group">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                    <a class="btn btn-danger" href="{% url 'plan-eliminar' plan.pk %}">Eliminar</a>
                </div>            
            </div>
        </div>
    </div>
</div>

nomina/templates/nomina/planes/modal-nuevo.html
{% load crispy_forms_tags %}

{{ form.media }}

<div class="modal fade" data-bs-backdrop="static" id="nuevoModal" tabindex="-1" role="dialog" aria-labelledby="nuevoModalLabel" aria-hidden="true">
    <form method="post" action="{% url 'plan-nuevo' %}" id="nuevo-form" autocomplete="off">
        {% csrf_token %}

        <div class="modal-dialog" role="document">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title" id="nuevoModalLabel">Nuevo Plan</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                
                <div class="modal-body">
                    {% crispy form %}
                </div>
    
                <div class="modal-footer">
                    <div class="btn-group" role="group">
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancelar</button>
                        <button type="submit" id="submit" class="btn btn-secondary" style="background-color: #782484; border-color: #782484;">Guardar Plan</button>
                    </div>            
                </div>
            </div>
        </div>
    </form>
</div>